version: 0.2

phases:
  install:
    commands:
      - cd cadmas-webclient
      - npm install
  build:
    commands:
      - npm run build-css
      - npm run build

artifacts:
  files:
    - '**/*'
  discard-paths: no
